/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicReadinessRouteImport } from './routes/academic-readiness'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CompareOffersRouteImport } from './routes/compare-offers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FindMyPathRouteImport } from './routes/find-my-path'
import { Route as FundRouteImport } from './routes/fund'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as OfferVaultRouteImport } from './routes/offer-vault'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as UniversitiesRouteImport } from './routes/universities'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicReadinessRoute = AcademicReadinessRouteImport.update({
  id: '/academic-readiness',
  path: '/academic-readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareOffersRoute = CompareOffersRouteImport.update({
  id: '/compare-offers',
  path: '/compare-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyPathRoute = FindMyPathRouteImport.update({
  id: '/find-my-path',
  path: '/find-my-path',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferVaultRoute = OfferVaultRouteImport.update({
  id: '/offer-vault',
  path: '/offer-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-readiness': typeof AcademicReadinessRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/applications': typeof ApplicationsRoute
  '/compare-offers': typeof CompareOffersRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/find-my-path': typeof FindMyPathRoute
  '/fund': typeof FundRoute
  '/guide': typeof GuideRoute
  '/intelligence': typeof IntelligenceRoute
  '/offer-vault': typeof OfferVaultRoute
  '/plan': typeof PlanRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sign-in': typeof SignInRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-readiness': typeof AcademicReadinessRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/applications': typeof ApplicationsRoute
  '/compare-offers': typeof CompareOffersRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/find-my-path': typeof FindMyPathRoute
  '/fund': typeof FundRoute
  '/guide': typeof GuideRoute
  '/intelligence': typeof IntelligenceRoute
  '/offer-vault': typeof OfferVaultRoute
  '/plan': typeof PlanRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sign-in': typeof SignInRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-readiness': typeof AcademicReadinessRoute
  '/account': typeof AccountRoute
  '/analyze': typeof AnalyzeRoute
  '/applications': typeof ApplicationsRoute
  '/compare-offers': typeof CompareOffersRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/find-my-path': typeof FindMyPathRoute
  '/fund': typeof FundRoute
  '/guide': typeof GuideRoute
  '/intelligence': typeof IntelligenceRoute
  '/offer-vault': typeof OfferVaultRoute
  '/plan': typeof PlanRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sign-in': typeof SignInRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-readiness'
    | '/account'
    | '/analyze'
    | '/applications'
    | '/compare-offers'
    | '/dashboard'
    | '/discover'
    | '/find-my-path'
    | '/fund'
    | '/guide'
    | '/intelligence'
    | '/offer-vault'
    | '/plan'
    | '/scholarships'
    | '/sign-in'
    | '/universities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-readiness'
    | '/account'
    | '/analyze'
    | '/applications'
    | '/compare-offers'
    | '/dashboard'
    | '/discover'
    | '/find-my-path'
    | '/fund'
    | '/guide'
    | '/intelligence'
    | '/offer-vault'
    | '/plan'
    | '/scholarships'
    | '/sign-in'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/academic-readiness'
    | '/account'
    | '/analyze'
    | '/applications'
    | '/compare-offers'
    | '/dashboard'
    | '/discover'
    | '/find-my-path'
    | '/fund'
    | '/guide'
    | '/intelligence'
    | '/offer-vault'
    | '/plan'
    | '/scholarships'
    | '/sign-in'
    | '/universities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicReadinessRoute: typeof AcademicReadinessRoute
  AccountRoute: typeof AccountRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CompareOffersRoute: typeof CompareOffersRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  FindMyPathRoute: typeof FindMyPathRoute
  FundRoute: typeof FundRoute
  GuideRoute: typeof GuideRoute
  IntelligenceRoute: typeof IntelligenceRoute
  OfferVaultRoute: typeof OfferVaultRoute
  PlanRoute: typeof PlanRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SignInRoute: typeof SignInRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-readiness': {
      id: '/academic-readiness'
      path: '/academic-readiness'
      fullPath: '/academic-readiness'
      preLoaderRoute: typeof AcademicReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-offers': {
      id: '/compare-offers'
      path: '/compare-offers'
      fullPath: '/compare-offers'
      preLoaderRoute: typeof CompareOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-path': {
      id: '/find-my-path'
      path: '/find-my-path'
      fullPath: '/find-my-path'
      preLoaderRoute: typeof FindMyPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-vault': {
      id: '/offer-vault'
      path: '/offer-vault'
      fullPath: '/offer-vault'
      preLoaderRoute: typeof OfferVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicReadinessRoute: AcademicReadinessRoute,
  AccountRoute: AccountRoute,
  AnalyzeRoute: AnalyzeRoute,
  ApplicationsRoute: ApplicationsRoute,
  CompareOffersRoute: CompareOffersRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  FindMyPathRoute: FindMyPathRoute,
  FundRoute: FundRoute,
  GuideRoute: GuideRoute,
  IntelligenceRoute: IntelligenceRoute,
  OfferVaultRoute: OfferVaultRoute,
  PlanRoute: PlanRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SignInRoute: SignInRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
