// AUTO-GENERATED by 05-sanity/generation/gen_schema_files.py. Not derived
// from a $defs entry -- verification_record.proposed_value and
// change_record.previous_value/proposed_value are declared in the JSON
// Schema as bare `{}` (untyped: "any value"), since a VerificationRecord or
// ChangeRecord can be checking a proposed value for any canonical field, of
// any type. Sanity has no native "any" field type, so this is the
// deterministic box every such value is wrapped in: `value` is always a
// string (the value's own text when it was already a string, or its
// canonical JSON serialization otherwise), and `value_type` records which
// primitive case applies (including 'null', since a verification record
// asserting "the correct value is genuinely absent" is meaningful domain
// data, not missing data -- it is never pruned the way an ordinary null is
// elsewhere in this pipeline).
import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'anyValueBox',
  title: 'Any Value',
  type: 'object',
  fields: [
    defineField({
      name: 'value',
      title: 'Value',
      type: 'text',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'value_type',
      title: 'Value Type',
      type: 'string',
      options: { list: ['string', 'number', 'boolean', 'json', 'null'] },
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: { title: 'value', subtitle: 'value_type' },
  },
})
