// AUTO-GENERATED by 05-sanity/generation/gen_schema_files.py. Not derived
// from a $defs entry -- extension_metadata.fields is a free-form,
// string-keyed map (arbitrary source-backed facts of heterogeneous value
// shape), and Sanity has no native arbitrary-map field type. This is the
// deterministic entry shape the transform (04-pipeline/
// normalized_to_sanity_ndjson_v1_2.py) converts each map entry into: one
// entry per original key, `value` always a string (the value as-is when the
// original was already a string, or its canonical JSON serialization
// otherwise), and `value_type` telling a reader which case it is so the
// original shape is always recoverable -- never a lossy stringified object.
import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'extensionMetadataFieldEntry',
  title: 'Extension Metadata Field Entry',
  type: 'object',
  fields: [
    defineField({
      name: 'key',
      title: 'Key',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'value',
      title: 'Value',
      type: 'text',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'value_type',
      title: 'Value Type',
      type: 'string',
      options: { list: ['string', 'json'] },
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: { title: 'key', subtitle: 'value' },
  },
})
